***REMOVED***

***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
      # - DATABASE_CLIENT=mongo
      # - DATABASE_HOST=devy3mrdbzlcosmosdb.documents.azure.com
      # - DATABASE_PORT=10255
      # - DATABASE_NAME=strapi
      # - DATABASE_USERNAME=devy3mrdbzlcosmosdb
      # - DATABASE_PASSWORD=251Rj4CNSQSJK8mF1x9DWhsuisMx4SAXkHd9alXN742SewMMSuZzipvhM8WAlgPW0Wq7I23NcFsApGPW1O4Pog==
      # - AUTHENTICATION_DATABASE=strapi
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***

***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***