version: '3'

services:
  strapi:
    container_name: strapi
    image: strapi/bca
    build:
        context: strapi
        dockerfile: Dockerfile
        args:
            STRAPI_VERSION: 3.2.5
    environment:
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - AUTHENTICATION_DATABASE=strapi
      - DATABASE_SSL=false
    ports:
      - 1337:1337
    volumes:
      - ./strapi/app:/srv/app
    depends_on:
      - db

  db:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always