version: '3'

services:
  strapi:
    container_name: strapi
    image: strapi/bca
    build:
        context: strapi
        dockerfile: Dockerfile
        args:
            STRAPI_VERSION: 3.2.5
    # env_file:
    #   - ./strapi/.env
    # environment:
    #   - DATABASE_CLIENT=${DATABASE_CLIENT}
    #   - DATABASE_HOST=${DATABASE_HOST}
    #   - DATABASE_PORT=${DATABASE_PORT}
    #   - DATABASE_NAME=${DATABASE_NAME}
    #   - DATABASE_USERNAME=${DATABASE_USERNAME}
    #   - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    #   - AUTHENTICATION_DATABASE=${AUTHENTICATION_DATABASE}
    #   - DATABASE_SSL=${DATABASE_SSL}
    ports:
      - 1337:1337
    networks:
      - strapi-app-network
    depends_on:
      - db

  db:
    container_name: mongo
    image: mongo:3.6
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017
    # volumes:
    #   - ./db:/data/db
    restart: always
    networks:
      - strapi-app-network

networks:
  strapi-app-network:
    driver: bridge