apiVersion : apps/v1
kind: Deployment
metadata:
  name: "devaks-6c99"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "devaks-6c99"
  template:
    metadata:
      labels:
        app: "devaks-6c99"
    spec:
      containers:
        - name: "devaks-6c99"
          image: "dev2xzbeeqyacr.azurecr.io/devaks"
          ports:
          - containerPort: 1337