apiVersion : apps/v1
kind: Deployment
metadata:
  name: "homecloneapp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "homecloneapp"
  template:
    metadata:
      labels:
        app: "homecloneapp"
    spec:
      containers:
        - name: "homecloneapp"
          image: "dev4gqggmqqacr.azurecr.io/devaks"
          ports:
          - containerPort: 80