apiVersion : apps/v1
kind: Deployment
metadata:
  name: "strapiapp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "strapiapp"
  template:
    metadata:
      labels:
        app: "strapiapp"
    spec:
      containers:
        - name: "strapiapp"
          image: "devgy2ryqcjacr.azurecr.io/devaks"
          ports:
          - containerPort: 1337
          env:
            - name: "DOCKER"
              value: "true"
            - name: "APP_NAME"
              value: "strapi-app"
            - name: "DATABASE_NAME"
              value: "strapi"
            - name: "DATABASE_PORT"
              value: "5432"
            - name: "DATABASE_SSL"
              value: "true"
            - name: "DATABASE_HOST"
              valueFrom:
                secretKeyRef:
                  name: "akv-secrets"
                  key: PSQLHOST
            - name: "DATABASE_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: "akv-secrets"
                  key: PSQLUID
            - name: "DATABASE_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "akv-secrets"
                  key: PSQLPWD
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
