apiVersion: v1
kind: Service
metadata:
    name: "devaks-6c99"
    labels:
        app: "devaks-6c99"
spec:
    type: LoadBalancer
    ports:
    - port: 1337
      targetPort: 1337
      protocol: TCP
      name: http
    selector:
        app: "devaks-6c99"