apiVersion: v1
kind: Service
metadata:
    name: "devqg9132f9aks-1f0b"
    labels:
        app: "devqg9132f9aks-1f0b"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "devqg9132f9aks-1f0b"