apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
      - name: strapi
        image: devy3mrdbzlacr.azurecr.io/strapi:latest
        env:
          - name: NAMESPACE
            value: "ns-strapi"
          # - name: "DATABASE_CLIENT"
          #   value: "mongo"
          # - name: "DATABASE_NAME"
          #   value: "strapi"
          # - name: "DATABASE_PORT"
          #   value: "10255"
          # - name: "DATABASE_HOST"
          #   value: "
          # - name: "DATABASE_USERNAME"
          #   value: "
          # - name: "DATABASE_PASSWORD"
          #   value: ""
          - name: "APP_NAME"
            value: "strapi-app"
        resources:
            requests:
              cpu: '1'
              memory: 3Gi
            limits:
              cpu: '1'
              memory: 3Gi
        ports:
        - containerPort: 1337
          name: strapi
---
apiVersion: v1
kind: Service
metadata:
  name: strapi
spec:
  type: LoadBalancer
  ports:
  - port: 1337
  selector:
    app: strapi