name: Promote Strapi
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: dev4gqggmqqacr.azurecr.io
        username: ${{ secrets.acr_login }}
        password: ${{ secrets.acr_password }}

    - name: Promote image to Build and push image to ACR
      id: build-image
      run: |
        docker tag dev4gqggmqqacr.azurecr.io/devaks:dev dev4gqggmqqacr.azurecr.io/devaks:test
        docker push dev4gqggmqqacr.azurecr.io/devaks:test

    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_devaks_kubeConfig }}
      id: login

    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep development | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace development`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: testing
        container-registry-url: dev4gqggmqqacr.azurecr.io
        container-registry-username: ${{ secrets.acr_login }}
        container-registry-password: ${{ secrets.acr_password }}
        secret-name: devaksdockerauth

    - uses: azure/k8s-deploy@v1.3
      with:
        namespace: testing
        manifests: |
          manifests/deployment-strapi.yml
          manifests/service-strapi.yml
        images: |
          dev4gqggmqqacr.azurecr.io/devaks:${{ github.sha }}
        imagepullsecrets: |
          devaksdockerauth
