name: Build, Test and Deploy - CI Workflow
on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: azure/docker-login@v1
      with:
        login-server: devgy2ryqcjacr.azurecr.io
        username: ${{ secrets.acr_devgy2ryqcjacr_username }}
        password: ${{ secrets.acr_devgy2ryqcjacr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/strapi" -f  "strapi/Dockerfile" -t devgy2ryqcjacr.azurecr.io/devaks:${{ github.sha }}
        docker push devgy2ryqcjacr.azurecr.io/devaks:${{ github.sha }}

    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_devaks_kubeConfig }}
      id: login

    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep dev-aksb474 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace dev-aksb474`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: dev-aksb474
        container-registry-url: devgy2ryqcjacr.azurecr.io
        container-registry-username: ${{ secrets.acr_devgy2ryqcjacr_username }}
        container-registry-password: ${{ secrets.acr_devgy2ryqcjacr_password }}
        secret-name: devaksdockerauth

    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: dev-aksb474
        manifests: |
          manifests/deployment-3.yml
          manifests/service-3.yml
        images: |
          devgy2ryqcjacr.azurecr.io/devaks:${{ github.sha }}
        imagepullsecrets: |
          devaksdockerauth
